config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/error'
  get 'imports/generate_report'
  get 'imports/parse_csv_file'
  get 'imports/start_quoting'
  root 'pages#main'

  devise_for :users

  resources :imports, only: %i[new create show index] do
    resources :quotes, only: %i[index show]
  end
  resources :users
end

app/models/application_record.rb
# class application model
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :property, autosave: true
  has_one :policy, autosave: true
  has_one :quote
  belongs_to :import

  enum marital_status: %I[
    married
    separated
    single
  ]

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :fico_score, presence: true
  validates :marital_status, presence: true
  validates :date_of_birth, presence: true
  validates :phone, presence: true
  validates :email, presence: true

  scope :with_success_quotes, lambda {
    left_outer_joins(:quote).where(
      quotes: { status: 'success' }
    )
  }

  delegate :premium, to: :policy, prefix: 'previous'
  delegate :premium, to: :quote, prefix: true
end

app/models/fail_reason.rb
class FailReason < ApplicationRecord
  belongs_to :import_report
end

app/models/import.rb
class Import < ApplicationRecord # :nodoc:
  belongs_to :partner

  has_many :quotes
  has_many :customers
  has_one :import_report
  has_many :fail_reasons, through: :import_report

  validates :file,   presence: true
  validates :status, presence: true
  validates :title,  presence: true

  enum status: %i[created started finished]

  mount_uploader :file, ImportUploader

  def file_path
    file.file.url
  end
end

app/models/import_report.rb
class ImportReport < ApplicationRecord
  belongs_to :import
  has_many :fail_reasons
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_many :imports
  has_many :users

  validates_uniqueness_of :key
end

app/models/policy.rb
# model Policy
class Policy < ApplicationRecord
  belongs_to :customer

  validates :carrier_name, presence: true
  validates :premium, presence: true
  validates :coverages, presence: true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :customer

  enum property_type: %I[
    condominium
    multifamily
    townhouse
    mobile_home
    duplex
    manufactured_home
    triplex
    rowhome
    apartment
    farm
    land_and_developed_lots
    single_family_detached
    pud
    four_plex
    other
  ]
  enum residency_type: %I[
    second_home
    primary_residence
    investment
  ]

  validates :property_type, presence: true
  validates :residency_type, presence: true
  validates :address_line1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

  def full_address
    "#{address_line1}, #{city}, #{state} #{zip}"
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :import
  belongs_to :customer
  paginates_per 20

  enum status: %I[success fail]
end

app/models/user.rb
# main class
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :partner, optional: true

  validates :role, presence: true
  enum role: %w[manager agent]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# class application controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def after_sign_in_path_for(resource)
    if resource.manager?
      imports_path
    elsif resource.agent?
      new_import_path
    else
      pages_error_path
    end
  end
end

app/controllers/concerns/20180709201128_change_role_type_for_user.rb
# ChangeRoleTypeForUsers
class ChangeRoleTypeForUser < ActiveRecord::Migration[5.1]
  def change
    change_column :users, :role, :integer, using: 'role::integer'
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController # :nodoc:
  before_action :manager?, except: %i[new show create]
  def index
    @imports = Import.all.page params[:page]
  end

  def new
    @import = Import.new
  end

  def create
    result = CreateImport.call(params: import_data)
    if result.success?
      redirect_to result.import
    else
      flash[:alert] = result.message
      render :new
    end
  end

  def show; end

  def parse_csv_file
    ParseCsv.call(import_id: params[:id])
    redirect_to imports_path
  end

  def start_quoting
    StartQuoting.call(import_id: params[:id])
    redirect_to imports_path
  end

  def generate_report
    report = CreateReport.call(import_id: params[:id])
    send_data report.csv, filename: 'Report.csv'
  end

  private

  def manager?
    if current_user.manager?
      true
    else
      redirect_to root_path, notice: "You don't have permissions!"
    end
  end

  def import_params
    params.require(:import).permit(:title, :file)
  end

  def import_data
    import_params.merge(partner_id: current_user.partner_id)
  end
end

app/controllers/pages_controller.rb
# PagesController
class PagesController < ApplicationController
  def main; end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = set_import.quotes.page params[:page]
  end

  def show
    @quote = set_quote
  end

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def set_import
    @import = Import.find(params[:import_id])
  end
end

app/controllers/users_controller.rb
# main class
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show; end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/imports/_form.html.erb
<%= form_with(model: import, multipart: true, local: true,:html => {:class => 'upload'} ) do |form| %>
  <div class='field'>
    <%= form.label :title, 'Title' %>
    <%= form.text_field :title,:id => 'input' %>
  </div>

  <div class='field'>
    <%= form.file_field :file,:id => 'choose_file' %>
  </div>

  <div class='actions'>
    <%= form.submit 'Upload',:class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/imports/index.html.erb
<!-- dummy -->
<!-- link_to "Export CSV", import_path(format: :csv) %> -->
<div class="import-file-table">
  <%= paginate @imports, window: 1 %>
  <table class="table table-hover table-color">
    <thead class="head-table thead-dark">
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Partner name</th>
        <th scope="col">Customers count</th>
        <th scope="col">Invalid count</th>
        <th scope="col">Quote count</th>
        <th scope="col">Action</th>
        <th scope="col">Report</th>
      </tr>
    </thead>
    <% @imports.each do |import| %>
      <tbody>
      <tr>
        <td>
          <%= link_to import.title, import.file.to_s %>
        </td>
        <td><%= import.partner.name %></td>
        <td><%= import.customers.count %></td>
        <td><%= import.fail_reasons.count %></td>
        <td><%= import.quotes.count %></td>
          <% if import.status == 'created' %>
          <td>
            <%= link_to('Start import', imports_parse_csv_file_path(id: import.id), class: 'btn btn-primary') %>
          </td>
          <td></td>
        <% else %>
          <td>
            <%= link_to('Start Quoting', imports_start_quoting_path(id: import.id), class: 'btn btn-secondary') %>
          </td>
          <td>
            <%= link_to 'Generate', imports_generate_report_path(id: import.id, format: :csv), class: 'btn btn-primary' %>
          </td>
        <% end %>
      </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/imports/new.html.erb
<div class="middle_block">
  <h1>Please,Upload File</h1>
  <%= render 'form', import: @import %>
</div>

app/views/imports/parse_csv_file.html.erb
Parsing file

app/views/imports/show.html.erb
  <div id="add_file_complete">
    <p>Thank you, we will reach you out</p>
    <%= link_to('Add new file', new_import_path, class: 'btn btn-primary go-to-new-import-btn') %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsuranceHouseService</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to("Sign out", destroy_user_session_path, method: :delete, :class => "btn btn-danger", :id => "sign_out") if user_signed_in? %>

    <% if user_signed_in? %>
      <% flash.each do |_, message| %>
        <div id="notice_wrapper_green">
          <h3 class="notice"><%= content_tag(:div, message) %></h3>
        </div>
      <% end %>
    <% else %>
      <% flash.each do |_, message| %>
        <div id="notice_wrapper_red">
          <h3 class="notice"><%= content_tag(:div, message) %></h3>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/main.html.erb
<div class="middle_block">
  <h1>Welcome to</h1>
  <h1>Insuranse House Service</h1>
  <% unless user_signed_in?%>
  <p>Please, Login If You Are Cooperator</p>
  <%= link_to '<button type="button", class="btn btn-primary", id="button1">Login</button>'.html_safe, new_user_session_path %>
  <% else %>
    <% if current_user.manager?%>
    <%= link_to '<button type="button", class="btn btn-primary", id="button1">Back To Dashboard</button>'.html_safe, imports_path %>
    <% elsif current_user.agent?%>
    <%= link_to '<button type="button", class="btn btn-primary", id="button1">Back To Dashboard</button>'.html_safe, new_import_path %>
    <% end %>
  <% end %>
</div>

app/views/quotes/index.html.erb
<h1>Quotes</h1>

<div class="container">
<%= paginate @quotes, window: 1 %>
<table class="table table-hover table-light">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">carrier_key</th>
      <th scope="col">status</th>
      <th scope="col">message</th>
      <th scope="col">premium</th>
      <th scope="col">coverages</th>
      <th scope="col">show</th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.id %></td>
        <td><%= quote.carrier_key %></td>
        <td><%= quote.status %></td>
        <td><%= quote.message %></td>
        <td><%= quote.premium %></td>
        <td><%= quote.coverages %></td>
        <td><%= link_to "Show details", import_quote_path(quote.import_id, quote) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @quotes, window: 1 %>
</div>

app/views/quotes/show.html.erb
<p>
  <strong>Carrier:</strong>
  <%= @quote.carrier_key %>
</p>
 
<p>
  <strong>Status:</strong>
  <%= @quote.status %>
</p>

<p>
  <strong>Message:</strong>
  <%= @quote.message %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @quote.premium %>
</p>

<p>
  <strong>Coverages:</strong>
  <%= @quote.coverages %>
</p>
<%= link_to 'Back', import_quotes_path %>